const state={batch:null};
const el=id=>document.getElementById(id);
const formData=form=>Object.fromEntries(new FormData(form).entries());
const requestID=prefix=>`${prefix}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function notify(message,error=false){el("notice").textContent=message;el("notice").style.borderColor=error?"#a83232":"#c58332"}
function meta(actor,prefix){return{actor,request_id:requestID(prefix),expected_revision:state.batch?.revision||0}}
function update(batch){state.batch=batch;el("selected").textContent=batch?batch.batch_id:"未选择批次";el("status").textContent=batch?.status||"—";el("revision").textContent=batch?`revision ${batch.revision}`:"revision —";el("evidence-link").classList.toggle("hidden",!batch);if(batch)el("evidence-link").href=`/api/v1/batches/${encodeURIComponent(batch.batch_id)}/evidence`;if(batch)el("record-output").textContent=JSON.stringify(batch,null,2)}
async function refresh(){try{const data=await api("/api/v1/batches");const box=el("batch-list");box.replaceChildren();data.batches.forEach(batch=>{const button=document.createElement("button");button.className="batch-item";button.innerHTML=`<strong>${batch.title}</strong><small>${batch.batch_id} · ${batch.status} · r${batch.revision}</small>`;button.onclick=async()=>update(await api(`/api/v1/batches/${encodeURIComponent(batch.batch_id)}`));box.append(button)});notify(`已载入 ${data.batches.length} 个批次`)}catch(e){notify(e.message,true)}}
async function submit(path,payload){try{const result=await api(path,{method:"POST",body:JSON.stringify(payload)});if(result.batch)update(result.batch);notify(result.idempotent_replay?"已复用相同 request_id 的结果":"操作已记录并写入审计链");await refresh();return result}catch(e){notify(e.message,true);throw e}}
el("create-form").onsubmit=async event=>{event.preventDefault();const d=formData(event.currentTarget);try{const result=await submit("/api/v1/batches",{...d,request_id:requestID("create")});update(result.batch)}catch{}};
el("consent-form").onsubmit=async event=>{event.preventDefault();if(!state.batch)return notify("请先选择批次",true);const d=formData(event.currentTarget);const payload={...meta(d.actor,"consent"),consent_id:d.consent_id,participant_code:d.participant_code,scope:["open_archive"],signed_at:new Date(d.signed_at).toISOString(),withdrawal_rule:d.withdrawal_rule,evidence_digest:d.evidence_digest,verified_by:d.verified_by};try{await submit(`/api/v1/batches/${state.batch.batch_id}/consents`,payload)}catch{}};
el("annotation-form").onsubmit=async event=>{event.preventDefault();if(!state.batch)return notify("请先选择批次",true);const d=formData(event.currentTarget);try{await submit(`/api/v1/batches/${state.batch.batch_id}/annotations`,{...meta(d.actor,"annotate"),segments:JSON.parse(d.segments)})}catch(e){notify(e.message,true)}};
function redactionPayload(){const d=formData(el("redaction-form"));return{d,payload:{...meta(d.actor,"redact"),marks:JSON.parse(d.marks),confirm_no_pii:el("redaction-form").elements.confirm_no_pii.checked}}}
el("preview").onclick=async()=>{if(!state.batch)return notify("请先选择批次",true);try{const {payload}=redactionPayload();const data=await api(`/api/v1/batches/${state.batch.batch_id}/redactions/preview`,{method:"POST",body:JSON.stringify({marks:payload.marks})});el("preview-output").textContent=JSON.stringify(data.preview,null,2);notify("预览未写入批次") }catch(e){notify(e.message,true)}};
el("redaction-form").onsubmit=async event=>{event.preventDefault();if(!state.batch)return notify("请先选择批次",true);try{const {payload}=redactionPayload();await submit(`/api/v1/batches/${state.batch.batch_id}/redactions`,payload)}catch(e){notify(e.message,true)}};
el("review-form").onsubmit=async event=>{event.preventDefault();if(!state.batch)return notify("请先选择批次",true);const d=formData(event.currentTarget);const changes=d.required_changes.split("\n").map(x=>x.trim()).filter(Boolean);try{await submit(`/api/v1/batches/${state.batch.batch_id}/reviews`,{...meta(d.actor,"review"),review_id:d.review_id,decision:d.decision,findings:d.findings,required_changes:changes})}catch{}};
el("release-form").onsubmit=async event=>{event.preventDefault();if(!state.batch)return notify("请先选择批次",true);const d=formData(event.currentTarget);try{await submit(`/api/v1/batches/${state.batch.batch_id}/release`,meta(d.actor,"release"))}catch{}};
el("load-audit").onclick=async()=>{if(!state.batch)return notify("请先选择批次",true);try{el("record-output").textContent=JSON.stringify(await api(`/api/v1/batches/${state.batch.batch_id}/audit?limit=100`),null,2)}catch(e){notify(e.message,true)}};
el("load-manifest").onclick=async()=>{if(!state.batch)return notify("请先选择批次",true);try{el("record-output").textContent=JSON.stringify(await api(`/api/v1/batches/${state.batch.batch_id}/manifest`),null,2)}catch(e){notify(e.message,true)}};
el("refresh").onclick=refresh;
const today=new Date();el("create-form").elements.collected_at.value=today.toISOString().slice(0,10);el("consent-form").elements.signed_at.value=today.toISOString().slice(0,16);refresh();
